-- code used to create table, role, etc. on snowflake worksheet: 
CREATE DATABASE NEWSDB
CREATE OR REPLACE TABLE NEWSDB.PUBLIC.NEWS (
	ID NUMBER(38,0),
	SOURCE VARCHAR(16777216),
	ARTICLE VARCHAR(16777216),
	CATEGORY VARCHAR(16777216),
	CONTENT VARCHAR(16777216),
	SENTIMENT VARCHAR(16777216),
	unique (ARTICLE),
	unique (CONTENT)
);

CREATE WAREHOUSE SNOW_WH
WITH
WAREHOUSE_SIZE = 'SMALL'
AUTO_SUSPEND = 300
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = FALSE;

CREATE ROLE user_role;
GRANT USAGE ON WAREHOUSE SNOW_WH TO ROLE user_role;
GRANT CREATE STAGE ON SCHEMA NEWSDB.PUBLIC TO ROLE user_role;
GRANT USAGE ON DATABASE NEWSDB TO ROLE user_role;
GRANT USAGE ON SCHEMA NEWSDB.PUBLIC TO ROLE user_role;
GRANT USAGE ON WAREHOUSE SNOW_WH TO ROLE user_role;
GRANT INSERT, UPDATE, DELETE ON TABLE NEWSDB.PUBLIC.NEWS TO ROLE user_role;

GRANT ROLE user_role TO SNOW_USER






